# Generated by Django 5.2.3 on 2026-03-12 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('channel', models.CharField(choices=[('linkedin', 'LinkedIn'), ('blog', 'Blog')], db_index=True, max_length=24)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('model', models.CharField(blank=True, max_length=128)),
                ('prompt_version', models.CharField(blank=True, max_length=64)),
                ('topic', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('posted', 'Posted'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=24)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='gops_content_stat_sched_idx')],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.CharField(choices=[('IE', 'Ireland'), ('RO', 'Romania'), ('US', 'United States'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=12)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('industry', models.CharField(blank=True, db_index=True, max_length=120)),
                ('company_name', models.CharField(db_index=True, max_length=255)),
                ('website_url', models.URLField(blank=True)),
                ('google_place_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('source', models.CharField(db_index=True, default='n8n', max_length=64)),
                ('status', models.CharField(choices=[('new', 'New'), ('evidence_collected', 'Evidence Collected'), ('reported', 'Reported'), ('scored', 'Scored'), ('draft_pending', 'Draft Pending'), ('in_sequence', 'In Sequence'), ('replied', 'Replied'), ('archived', 'Archived')], db_index=True, default='new', max_length=32)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='growth_lead_status_created_idx'), models.Index(fields=['market', 'industry'], name='gops_lead_mkt_ind_idx')],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('linkedin_url', models.URLField(blank=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='growth_ops.lead')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LeadScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('score', models.IntegerField(db_index=True)),
                ('bucket', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], db_index=True, max_length=1)),
                ('reason_codes', models.JSONField(blank=True, default=list)),
                ('recommendation', models.JSONField(blank=True, default=dict)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='growth_ops.lead')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OutboundDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('linkedin', 'LinkedIn')], db_index=True, default='email', max_length=32)),
                ('sequence_step', models.PositiveSmallIntegerField(db_index=True, default=1)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('prompt_version', models.CharField(blank=True, max_length=64)),
                ('proof_points', models.JSONField(blank=True, default=list)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('evidence_check', models.JSONField(blank=True, default=dict)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_outbound_drafts', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_drafts', to='growth_ops.contact')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_drafts', to='growth_ops.lead')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OutboundSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('provider', models.CharField(default='django_smtp', max_length=64)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('replied', 'Replied')], db_index=True, default='queued', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='growth_ops.outbounddraft')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PromptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('prompt_name', models.CharField(db_index=True, max_length=128)),
                ('prompt_version', models.CharField(db_index=True, max_length=64)),
                ('model', models.CharField(db_index=True, max_length=128)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('output_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('invalid_schema', 'Invalid Schema')], db_index=True, max_length=32)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['prompt_name', 'prompt_version'], name='growth_prompt_name_ver_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('stopped_on_reply', 'Stopped On Reply'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=24)),
                ('step', models.PositiveSmallIntegerField(db_index=True, default=1)),
                ('next_send_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='growth_ops.lead')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WebsiteEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('evidence_type', models.CharField(choices=[('lighthouse_json', 'Lighthouse JSON'), ('pagespeed_json', 'PageSpeed JSON'), ('homepage_headers', 'Homepage Headers'), ('robots_txt', 'robots.txt'), ('sitemap_xml', 'sitemap.xml'), ('homepage_html_snippet', 'Homepage HTML Snippet'), ('contact_html_snippet', 'Contact HTML Snippet'), ('service_html_snippet', 'Service HTML Snippet'), ('tech_fingerprint', 'Tech Fingerprint'), ('other', 'Other')], db_index=True, max_length=64)),
                ('url', models.URLField(blank=True)),
                ('tool', models.CharField(blank=True, db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_evidence', to='growth_ops.lead')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WebsiteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('model', models.CharField(db_index=True, max_length=128)),
                ('prompt_version', models.CharField(db_index=True, max_length=64)),
                ('evidence_ids', models.JSONField(blank=True, default=list)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_reports', to='growth_ops.lead')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('linkedin', 'LinkedIn')], db_index=True, default='email', max_length=32)),
                ('thread_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('from_email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('classification', models.CharField(choices=[('interested', 'Interested'), ('needs_more_info', 'Needs More Info'), ('not_now', 'Not Now'), ('not_a_fit', 'Not A Fit'), ('unsubscribe', 'Unsubscribe'), ('out_of_office', 'Out Of Office'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=32)),
                ('suggested_reply', models.TextField(blank=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_messages', to='growth_ops.lead')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['approval_status', 'classification'], name='growth_inbox_status_class_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['lead', 'email'], name='growth_contact_lead_email_idx'),
        ),
        migrations.AddIndex(
            model_name='leadscore',
            index=models.Index(fields=['bucket', 'score'], name='growth_score_bucket_score_idx'),
        ),
        migrations.AddIndex(
            model_name='outbounddraft',
            index=models.Index(fields=['approval_status', 'created_at'], name='gops_draft_stat_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='outbounddraft',
            index=models.Index(fields=['lead', 'sequence_step'], name='growth_draft_lead_step_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundsend',
            index=models.Index(fields=['status', 'created_at'], name='growth_send_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='sequence',
            index=models.Index(fields=['status', 'next_send_at'], name='growth_seq_status_nextsend_idx'),
        ),
        migrations.AddIndex(
            model_name='websiteevidence',
            index=models.Index(fields=['lead', 'evidence_type'], name='growth_evidence_lead_type_idx'),
        ),
        migrations.AddIndex(
            model_name='websitereport',
            index=models.Index(fields=['lead', 'created_at'], name='growth_report_lead_created_idx'),
        ),
    ]
