# Generated by Django 5.2.3 on 2025-06-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='default-project.png', upload_to='media/'),
        ),
    ]
