# Generated by Django 5.2.3 on 2025-08-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='/default-project.png', upload_to=''),
        ),
    ]
