# Generated by Django 5.2.3 on 2025-08-22 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('service_type', models.CharField(choices=[('web_development', 'Web Development'), ('maintenance', 'Website Maintenance'), ('consultation', 'Technical Consultation'), ('optimization', 'Performance Optimization')], max_length=20)),
                ('short_description', models.CharField(help_text='Brief description for cards', max_length=200)),
                ('description', models.TextField()),
                ('features', models.TextField(help_text='One feature per line')),
                ('starting_price', models.CharField(blank=True, help_text="e.g., 'From £500' or 'Contact for Quote'", max_length=50)),
                ('delivery_time', models.CharField(blank=True, help_text="e.g., '2-3 weeks'", max_length=50)),
                ('icon', models.CharField(default='code', help_text='Lucide icon name', max_length=50)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Order of display')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('project_details', models.TextField()),
                ('budget_range', models.CharField(blank=True, choices=[('under_1k', 'Under £1,000'), ('1k_5k', '£1,000 - £5,000'), ('5k_10k', '£5,000 - £10,000'), ('10k_plus', '£10,000+'), ('not_sure', 'Not sure yet')], max_length=20)),
                ('timeline', models.CharField(blank=True, choices=[('asap', 'ASAP'), ('1_month', 'Within 1 month'), ('2_3_months', '2-3 months'), ('flexible', 'Flexible')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website_url', models.URLField(blank=True, help_text='Current website if any')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded', models.BooleanField(default=False)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
