# Generated by Django 5.2.3 on 2025-08-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_service_serviceinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('issuing_organization', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=100)),
                ('credential_url', models.URLField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='serviceinquiry',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Service Inquiries'},
        ),
    ]
