# Generated by Django 5.2.3 on 2025-08-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_credential_alter_serviceinquiry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
