# Generated by Django 5.2.3 on 2025-08-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_credential_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack_ro',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
