# Generated by Django 5.2.3 on 2025-08-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_project_description_en_project_description_ro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_en',
            field=models.TextField(help_text='Brief description of the post', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_ro',
            field=models.TextField(help_text='Brief description of the post', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='read_time_en',
            field=models.IntegerField(blank=True, help_text='Estimated read time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='read_time_ro',
            field=models.IntegerField(blank=True, help_text='Estimated read time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags_en',
            field=models.CharField(help_text='Comma-separated tags', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags_ro',
            field=models.CharField(help_text='Comma-separated tags', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_ro',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='delivery_time_en',
            field=models.CharField(blank=True, help_text="e.g., '2-3 weeks'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='delivery_time_ro',
            field=models.CharField(blank=True, help_text="e.g., '2-3 weeks'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_en',
            field=models.CharField(help_text='Brief description for cards', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_ro',
            field=models.CharField(help_text='Brief description for cards', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='starting_price_en',
            field=models.CharField(blank=True, help_text="e.g., 'From £500' or 'Contact for Quote'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='starting_price_ro',
            field=models.CharField(blank=True, help_text="e.g., 'From £500' or 'Contact for Quote'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='level_en',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], default='Beginner', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='level_ro',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], default='Beginner', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serviceinquiry',
            name='budget_range',
            field=models.CharField(blank=True, choices=[('under_1k', 'Under €1,000'), ('1k_5k', '€1,000 - €5,000'), ('5k_10k', '€5,000 - €10,000'), ('10k_plus', '€10,000+'), ('not_sure', 'Not sure yet')], max_length=20),
        ),
    ]
