# Generated by Django 5.2.3 on 2025-10-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_blogpost_content_en_blogpost_content_ro_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
