# Generated by Django 5.2.3 on 2025-10-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_delete_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_challenge',
            field=models.TextField(blank=True, help_text="What was the client's problem?", null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='my_solution',
            field=models.TextField(blank=True, help_text='What did you build for them?', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='the_result',
            field=models.TextField(blank=True, help_text='What was the positive outcome?', null=True),
        ),
    ]
