# Generated by Django 5.2.3 on 2025-10-08 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_project_client_challenge_project_my_solution_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credential',
        ),
    ]
