# Generated by Django 5.2.3 on 2025-10-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_delete_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='features_en',
            field=models.TextField(help_text='One feature per line', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='features_ro',
            field=models.TextField(help_text='One feature per line', null=True),
        ),
    ]
