# Generated by Django 5.2.3 on 2025-10-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_service_features_en_service_features_ro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tech_stack_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tech_stack_ro',
        ),
        migrations.AddField(
            model_name='project',
            name='client_challenge_en',
            field=models.TextField(blank=True, help_text="What was the client's problem?", null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_challenge_ro',
            field=models.TextField(blank=True, help_text="What was the client's problem?", null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='my_solution_en',
            field=models.TextField(blank=True, help_text='What did you build for them?', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='my_solution_ro',
            field=models.TextField(blank=True, help_text='What did you build for them?', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='the_result_en',
            field=models.TextField(blank=True, help_text='What was the positive outcome?', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='the_result_ro',
            field=models.TextField(blank=True, help_text='What was the positive outcome?', null=True),
        ),
    ]
