# Generated by Django 5.2.3 on 2025-10-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_remove_project_tech_stack_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_es',
            field=models.TextField(help_text='Brief description of the post', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='read_time_es',
            field=models.IntegerField(blank=True, help_text='Estimated read time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags_es',
            field=models.CharField(help_text='Comma-separated tags', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_challenge_es',
            field=models.TextField(blank=True, help_text="What was the client's problem?", null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='my_solution_es',
            field=models.TextField(blank=True, help_text='What did you build for them?', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='the_result_es',
            field=models.TextField(blank=True, help_text='What was the positive outcome?', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='delivery_time_es',
            field=models.CharField(blank=True, help_text="e.g., '2-3 weeks'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='features_es',
            field=models.TextField(help_text='One feature per line', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_es',
            field=models.CharField(help_text='Brief description for cards', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='starting_price_es',
            field=models.CharField(blank=True, help_text="e.g., 'From £500' or 'Contact for Quote'", max_length=50, null=True),
        ),
    ]
