# Generated by Django 5.2.3 on 2025-11-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_blogpost_content_es_blogpost_excerpt_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinquiry',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='GPT generated summary'),
        ),
        migrations.AddField(
            model_name='serviceinquiry',
            name='is_analyzed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceinquiry',
            name='lead_score',
            field=models.IntegerField(default=0, help_text='1-10 score based on fit'),
        ),
        migrations.AddField(
            model_name='serviceinquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('analyzed', 'AI Analyzed'), ('approved', 'Approved (Link Sent)'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
    ]
