# Generated by Django 5.2.3 on 2025-12-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_serviceinquiry_ai_summary_serviceinquiry_is_analyzed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinquiry',
            name='ai_email_draft',
            field=models.TextField(blank=True, help_text='AI-generated response draft'),
        ),
    ]
