# Generated by Django 5.2.3 on 2025-12-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_serviceinquiry_ai_email_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinquiry',
            name='ai_analysis_raw',
            field=models.TextField(blank=True, help_text='Raw AI analysis data'),
        ),
    ]
