# Generated by Django 5.2.3 on 2025-12-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_serviceinquiry_ai_analysis_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performance_score', models.IntegerField(blank=True, null=True)),
                ('accessibility_score', models.IntegerField(blank=True, null=True)),
                ('raw_audit_data', models.JSONField(blank=True, null=True)),
                ('ai_strategy_email', models.TextField(blank=True, help_text='GPT-4 Generated Outreach')),
            ],
        ),
    ]
