# Generated by Django 5.2.3 on 2026-02-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_siteaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='starting_price',
            field=models.CharField(blank=True, help_text='Contact for Quote', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='starting_price_en',
            field=models.CharField(blank=True, help_text='Contact for Quote', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='starting_price_es',
            field=models.CharField(blank=True, help_text='Contact for Quote', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='starting_price_ro',
            field=models.CharField(blank=True, help_text='Contact for Quote', max_length=50, null=True),
        ),
    ]
